### ISSUE TITLE
Inlines with extra set to 0 are unsubmittable

### ISSUE THREAD

**Issue by kezabelle** [callowayproject/django-admintheme#2]
The last time I used anything other than:

```
class MyInline(StackedInline):
    extra = 0
```

was prior to Django 1.2 bringing Javascript based `add another` (where previously it required a POST/Redirect/GET to get another one), as it means the admin isn't clogged up with inlines which may never get filled in.

Under normal Django, this works fine:
![before](http://i.imgur.com/u74Xdcd.png)
Note that it is:
- collapsed;
- will submit just fine, because it's empty, and Django knows that (I think it probably triggers `has_changed() == False` internally)

Using `admintheme`:
![after](http://i.imgur.com/v4aA6e1.png)
Note that this is:
- not collapsed;
- not filled in, but I have tried to submit it anyway. Instead, it hijacks the submit and displays the info tooltip.
- the `add another` link suffers from the problem highlighted in #1

**Comment by coordt** [comment]
Thanks for reporting these issues and your patience. I just finished giving a presentation I had been cramming for and will look at these issues tonight.

**Comment by coordt** [comment]
Can you try the latest HEAD version? I can't reproduce it there. I may have inadvertently fixed it after the initial release.

**Comment by kezabelle** [comment]
Tested against 3c1a5cd476893184461b4dff3e5d7fc9ecb389d7; seems to be fixed.
